/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.GUI_Funcionarios;
import View.GUI_Livros;

public class GUI_OpcoesBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_OpcoesBiblioteca.class.getName());

    /**
     * Creates new form Biblioteca
     */
    public GUI_OpcoesBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBiblioteca = new javax.swing.JPanel();
        LblTituloBiblioteca = new javax.swing.JLabel();
        BtnFuncionarios = new javax.swing.JButton();
        BtnLivros = new javax.swing.JButton();
        BtnPagamentos = new javax.swing.JButton();
        BtnEmprestimos = new javax.swing.JButton();
        BtnUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlBiblioteca.setToolTipText("");
        PnlBiblioteca.setName(""); // NOI18N

        LblTituloBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblTituloBiblioteca.setText("Biblioteca");
        LblTituloBiblioteca.setAlignmentX(0.5F);

        BtnFuncionarios.setText("Funcionários");
        BtnFuncionarios.addActionListener(this::BtnFuncionariosActionPerformed);

        BtnLivros.setText("Livros");
        BtnLivros.addActionListener(this::BtnLivrosActionPerformed);

        BtnPagamentos.setText("Pagamentos");
        BtnPagamentos.addActionListener(this::BtnPagamentosActionPerformed);

        BtnEmprestimos.setText("Empréstimos");
        BtnEmprestimos.addActionListener(this::BtnEmprestimosActionPerformed);

        BtnUsuarios.setText("Usuários");
        BtnUsuarios.addActionListener(this::BtnUsuariosActionPerformed);

        javax.swing.GroupLayout PnlBibliotecaLayout = new javax.swing.GroupLayout(PnlBiblioteca);
        PnlBiblioteca.setLayout(PnlBibliotecaLayout);
        PnlBibliotecaLayout.setHorizontalGroup(
            PnlBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBibliotecaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PnlBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEmprestimos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlBibliotecaLayout.createSequentialGroup()
                        .addComponent(BtnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(BtnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlBibliotecaLayout.createSequentialGroup()
                        .addComponent(BtnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(PnlBibliotecaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(LblTituloBiblioteca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlBibliotecaLayout.setVerticalGroup(
            PnlBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBibliotecaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LblTituloBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PnlBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFuncionariosActionPerformed
        this.dispose();
        
        GUI_Funcionarios guiFunc = new GUI_Funcionarios(); 
        guiFunc.setLocationRelativeTo(null);
        guiFunc.setVisible(true);
        
    }//GEN-LAST:event_BtnFuncionariosActionPerformed

    private void BtnPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagamentosActionPerformed
    GUI_Pagamento guiPag = new GUI_Pagamento(); 
        
    this.dispose();
        
    guiPag.setLocationRelativeTo(null);
    guiPag.setVisible(true);        }//GEN-LAST:event_BtnPagamentosActionPerformed

    private void BtnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLivrosActionPerformed
        GUI_Livros guiLiv = new GUI_Livros(); 
        
    this.dispose();
        
    guiLiv.setLocationRelativeTo(null);
    guiLiv.setVisible(true);        
    }//GEN-LAST:event_BtnLivrosActionPerformed

    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
     GUI_Usuario guiUsua = new GUI_Usuario(); 
        
    this.dispose();
        
    guiUsua.setLocationRelativeTo(null);
    guiUsua.setVisible(true);     }//GEN-LAST:event_BtnUsuariosActionPerformed

    private void BtnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmprestimosActionPerformed
     GUI_Emprestimo_Devolucao guiEmDev = new GUI_Emprestimo_Devolucao();
     
     this.dispose();
     
     guiEmDev.setLocationRelativeTo(null);
     guiEmDev.setVisible(true);
    }//GEN-LAST:event_BtnEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_OpcoesBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEmprestimos;
    private javax.swing.JButton BtnFuncionarios;
    private javax.swing.JButton BtnLivros;
    private javax.swing.JButton BtnPagamentos;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JLabel LblTituloBiblioteca;
    private javax.swing.JPanel PnlBiblioteca;
    // End of variables declaration//GEN-END:variables
}
