/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JTextField;
import javax.swing.JOptionPane;
import Controller.UsuarioConn;

public class GUI_Usuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_Usuario.class.getName());

    /**
     * Creates new form GUI_Usuario
     */
    public GUI_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtTabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PnlPainelCadastro = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblIdade = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        TxtIdade = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        BtnCadastrar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblTUsuario = new javax.swing.JTable();
        BtnVoltar = new javax.swing.JButton();

        TxtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TxtTabela);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuários");

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblTitulo.setText("Usuário");
        LblTitulo.setAlignmentX(0.5F);

        LblIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblIdade.setText("Idade:");
        LblIdade.setAlignmentX(0.5F);

        LblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblNome.setText("Nome:");
        LblNome.setAlignmentX(0.5F);

        TxtNome.addActionListener(this::TxtNomeActionPerformed);

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(this::BtnCadastrarActionPerformed);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(this::BtnCancelarActionPerformed);

        TblTUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Idade", "Livros_Emprestados"
            }
        ));
        jScrollPane3.setViewportView(TblTUsuario);

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(this::BtnVoltarActionPerformed);

        javax.swing.GroupLayout PnlPainelCadastroLayout = new javax.swing.GroupLayout(PnlPainelCadastro);
        PnlPainelCadastro.setLayout(PnlPainelCadastroLayout);
        PnlPainelCadastroLayout.setHorizontalGroup(
            PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblIdade)
                                    .addComponent(LblNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlPainelCadastroLayout.createSequentialGroup()
                                        .addComponent(TxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(BtnCadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnCancelar))
                                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnVoltar)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PnlPainelCadastroLayout.setVerticalGroup(
            PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPainelCadastroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnCadastrar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnVoltar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        TxtNome.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPainelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
    
        if (getTxtNome().getText().isEmpty()|| getTxtIdade().getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Todos os Campos devem Estar Preenchidos", "Alerta", JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        try {
            
            int idade = Integer.parseInt(getTxtIdade().getText());
                
                UsuarioConn conn = new UsuarioConn();
                
                conn.cadastrarUsuario(getTxtNome().getText(), idade);
                
                JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Quantidade deve ser um Número Válido", "Erro", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
    GUI_OpcoesBiblioteca guiPrinc = new GUI_OpcoesBiblioteca(); 
        
    this.dispose();
        
    guiPrinc.setLocationRelativeTo(null);
    guiPrinc.setVisible(true);    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
    GUI_OpcoesBiblioteca guiPrinc = new GUI_OpcoesBiblioteca(); 
        
    this.dispose();
        
    guiPrinc.setLocationRelativeTo(null);
    guiPrinc.setVisible(true);    }//GEN-LAST:event_BtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_Usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblIdade;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlPainelCadastro;
    private javax.swing.JTable TblTUsuario;
    private javax.swing.JTextField TxtIdade;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTable TxtTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtIdade() {
        return TxtIdade;
    }

    public void setTxtIdade(JTextField TxtIdade) {
        this.TxtIdade = TxtIdade;
    }

    public JTextField getTxtNome() {
        return TxtNome;
    }

    public void setTxtNome(JTextField TxtNome) {
        this.TxtNome = TxtNome;
    }


}
